# Generated by Django 4.2.6 on 2023-10-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_currency_options'),
        ('consumer', '0003_alter_consumer_options_alter_costgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='default_currency',
            field=models.ForeignKey(default=9624, on_delete=django.db.models.deletion.CASCADE, to='main.currency'),
        ),
    ]
