# Generated by Django 4.2.6 on 2023-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=255)),
                ('alphabetic_code', models.CharField(max_length=3)),
                ('numeric_code', models.PositiveIntegerField()),
            ],
        ),
    ]
